Repository JDaniielC/almocin, pull requests merged in 2024-06, with the labels that each got.

#20 FEAT: Cardapio e Categoria
  backend/src/controllers/category.controller.ts
  backend/src/controllers/menu.controller.ts
  backend/src/controllers/test.controller.ts
  backend/src/database/index.ts
  backend/src/di/index.ts
  backend/src/di/injector.ts
  backend/src/entities/base.entity.ts
  backend/src/entities/category.entity.ts
  backend/src/entities/item-menu.entity.ts
  backend/src/entities/test.entity.ts
  backend/src/models/base.model.ts
  backend/src/models/category.model.ts
  backend/src/models/item-menu.model.ts
  backend/src/models/test.model.ts
  backend/src/repositories/base.repository.ts
  backend/src/repositories/category.repository.ts
  backend/src/repositories/menu.repository.ts
  backend/src/repositories/other.repository.ts
  backend/src/repositories/test.repository.ts
  backend/src/routes/index.ts
  backend/src/services/category.service.ts
  backend/src/services/menu.service.ts
  backend/src/services/test.service.ts
  backend/tests/controllers/test.controller.spec.ts
  backend/tests/controllers/test.steps.ts
  backend/tests/services/test.service.spec.ts
  backend/tests/services/test.service.steps.ts
Labels: enhancement

#13 Add .features files of estimed time delivery and shopping cart
  .husky/pre-commit
  backend/tests/features/carrinho_compras.feature
  backend/tests/features/tempo_entrega.feature
  frontend/cypress/e2e/features/tests/carrinho_compras.feature
  frontend/cypress/e2e/features/tests/tempo_entrega.feature
Labels: documentation

#14 Menu and Category features.
  backend/tests/features/category-service.feature
  backend/tests/features/category.feature
  backend/tests/features/menu-service.feature
  backend/tests/features/menu.feature
  backend/tests/features/tests-service.feature
  backend/tests/features/tests.feature
Labels: documentation

#27 Feature of Sharing Link and Statistics Page
  backend/tests/features/statistics.feature
  frontend/cypress/e2e/features/tests/estatistica.feature
  frontend/cypress/e2e/features/tests/sharing_link.feature
Labels: documentation

#37 feat: backend src with order implementation
  backend/src/controllers/order.controller.ts
  backend/src/database/index.ts
  backend/src/di/index.ts
  backend/src/entities/order.entity.ts
  backend/src/models/order.model.ts
  backend/src/repositories/order.repository.ts
  backend/src/routes/index.ts
  backend/src/services/order.service.ts
  backend/src/types/order.ts
  backend/src/utils/errors/http.error.ts:Zone.Identifier
Labels: enhancement

#44 backend de order finalizado função getOrderByUserId adicionada
  backend/src/controllers/order.controller.ts
  backend/src/database/index.ts
  backend/src/repositories/order.repository.ts
  backend/src/services/order.service.ts
Labels: good first issue

#39 Feat: Statistic implementation
  backend/src/controllers/stats.controller.ts
  backend/src/services/stats.service.ts
  backend/tests/controllers/stats.controller.spec.ts
Labels: good first issue

#46 Login
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/login.controller.ts
  backend/src/controllers/register.controller.ts
  backend/src/core/authentication.ts
  backend/src/di/index.ts
  backend/src/entities/user.entity.ts
  backend/src/models/user.model.ts
  backend/src/repositories/user.repository.ts
  backend/src/routes/index.ts
  backend/src/services/login.service.ts
  backend/src/services/register.service.ts
  backend/src/utils/validation/validation.ts
  backend/src/utils/validation/validationMessages.ts
  backend/tests/features/login.feature
  backend/tsconfig.json
Labels: enhancement, help wanted

#40 Test: Menu steps
  backend/jest.config.js
  backend/src/controllers/menu.controller.ts
  backend/src/controllers/register.controller.ts
  backend/src/core/authentication.ts
  backend/src/env.ts
  backend/src/repositories/base.repository.ts
  backend/src/repositories/category.repository.ts
  backend/src/repositories/menu.repository.ts
  backend/src/repositories/order.repository.ts
  backend/src/repositories/user.repository.ts
  backend/src/services/login.service.ts
  backend/src/services/menu.service.ts
  backend/src/services/register.service.ts
  backend/src/utils/auth/generateToken.ts
  backend/src/utils/validation/validationMessages.ts
  backend/tests/controllers/menu.steps.ts
  backend/tests/controllers/register.steps.ts
  backend/tests/features/menu-service.feature
  backend/tests/features/menu.feature
  backend/tests/features/register.feature
  backend/tests/services/menu.steps.ts
  backend/tests/utils/formatParams.ts
  backend/tests/utils/mock.ts
Labels: documentation

#55 test: implementation of service and controller tests for the shopping cart in back-end
  backend/src/controllers/order.controller.ts
  backend/src/models/order.model.ts
  backend/src/services/order.service.ts
  backend/tests/controllers/shoping_cart.steps.ts
  backend/tests/features/carrinho_compras-service.feature
  backend/tests/features/carrinho_compras.feature
  backend/tests/features/tempo_entrega-service.feature
  backend/tests/services/shopping_cart.steps.ts
  frontend/package-lock.json
Labels: good first issue
