Repository JDaniielC/almocin, pull requests merged in 2024-07, with the labels that each got.

#58 Feat: admin module
  .gitignore
  backend/src/controllers/login.controller.ts
  backend/src/controllers/register.controller.ts
  backend/src/entities/category.entity.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Provider.tsx
  frontend/src/app/admin/components/baseLayout/index.module.css
  frontend/src/app/admin/components/baseLayout/index.tsx
  frontend/src/app/admin/components/listItem/index.module.css
  frontend/src/app/admin/components/listItem/index.tsx
  frontend/src/app/admin/context/CategoryContext/index.tsx
  frontend/src/app/admin/context/CategoryContext/reducer.ts
  frontend/src/app/admin/context/CategoryContext/service.ts
  frontend/src/app/admin/context/CategoryContext/types.ts
  frontend/src/app/admin/context/menuContext/index.tsx
  frontend/src/app/admin/context/menuContext/reducer.ts
  frontend/src/app/admin/context/menuContext/service.ts
  frontend/src/app/admin/context/menuContext/types.ts
  frontend/src/app/admin/context/userContext/index.tsx
  frontend/src/app/admin/context/userContext/reducer.ts
  frontend/src/app/admin/context/userContext/service.ts
  frontend/src/app/admin/context/userContext/types.ts
  frontend/src/app/admin/forms/CategoryForm.ts
  frontend/src/app/admin/forms/MenuForm.ts
  frontend/src/app/admin/forms/UserForm.ts
  frontend/src/app/admin/models/CategoryModel.ts
  frontend/src/app/admin/models/ItemMenuModel.ts
  frontend/src/app/admin/models/UserModel.ts
  frontend/src/app/admin/pages/adminPage/index.tsx
  frontend/src/app/admin/pages/categoryPage/index.module.css
  frontend/src/app/admin/pages/categoryPage/index.tsx
  frontend/src/app/admin/pages/menuPage/index.module.css
  frontend/src/app/admin/pages/menuPage/index.tsx
  frontend/src/app/admin/pages/userPage/index.module.css
  frontend/src/app/admin/pages/userPage/index.tsx
  frontend/src/app/admin/types/components-props.ts
  frontend/src/app/login/pages/loginPage/index.tsx
  frontend/src/app/login/pages/registerPage/index.tsx
  frontend/src/shared/components/Loading/index.module.css
  frontend/src/shared/components/Loading/index.tsx
  frontend/src/shared/components/model/index.module.css
  frontend/src/shared/components/model/index.tsx
  frontend/src/shared/types/category.ts
  package-lock.json
  package.json
Labels: enhancement

#60 Implementation of stats page
  frontend/src/App.tsx
  frontend/src/Provider.tsx
  frontend/src/app/admin/context/statsContext/index.tsx
  frontend/src/app/admin/context/statsContext/reducer.ts
  frontend/src/app/admin/context/statsContext/service.ts
  frontend/src/app/admin/context/statsContext/types.ts
  frontend/src/app/admin/pages/statsPage/index.module.css
  frontend/src/app/admin/pages/statsPage/index.tsx
  frontend/src/app/admin/types/components-props.ts
Labels: good first issue

#61 Adjusting stats page and stats filter
  backend/src/types/stats.ts
  frontend/src/app/admin/pages/statsPage/index.tsx
Labels: bug
